"""Small, authored topic packs available even without an external dictionary."""

from .content import LEXICONS

# Definitions are source content, not conclusions of the letter/grid solvers.
PACKS = {
    **LEXICONS,
    "space": (
        ("PLANET", "A rounded body orbiting a star that has cleared its orbital neighbourhood"),
        ("STAR", "A luminous celestial body powered by nuclear fusion during its main sequence"),
        ("MOON", "A natural satellite orbiting a planet or another nonstellar body"),
        ("COMET", "An icy small body that can develop a glowing coma near the Sun"),
        ("ORBIT", "The curved path of a body moving around another under gravity"),
        ("GALAXY", "A gravitationally bound system of stars, gas, dust and dark matter"),
        ("NEBULA", "An interstellar cloud of gas and dust"),
        ("METEOR", "The streak of light produced when a space rock enters an atmosphere"),
        ("ASTEROID", "A small rocky body orbiting the Sun"),
        ("ROCKET", "A vehicle propelled by expelling material in the opposite direction"),
        ("TELESCOPE", "An instrument that collects radiation to observe distant objects"),
        ("ECLIPSE", "An event in which one celestial body obscures another or enters its shadow"),
        ("CRATER", "A bowl-shaped depression often formed by an impact"),
        ("GRAVITY", "The attraction associated with mass and energy"),
    ),
    "animals": (
        ("TIGER", "A large Asian cat with dark vertical stripes"),
        ("LION", "A large social cat whose adult males typically have manes"),
        ("ZEBRA", "An African equine with black-and-white stripes"),
        ("GIRAFFE", "A very tall African mammal with a long neck and a spotted coat"),
        ("ELEPHANT", "A large mammal with a trunk and broad ears"),
        ("RABBIT", "A long-eared mammal with powerful hind legs and a short tail"),
        ("OTTER", "A semiaquatic carnivorous mammal with dense fur"),
        ("DOLPHIN", "A toothed whale typically having a curved dorsal fin and a beaklike snout"),
        ("EAGLE", "A large bird of prey with a hooked beak and strong talons"),
        ("PENGUIN", "A flightless seabird adapted to swimming with flipperlike wings"),
        ("TURTLE", "A reptile whose body is enclosed in a bony shell"),
        ("SNAKE", "A limbless reptile with an elongated body"),
        ("BEETLE", "An insect with hardened forewings covering its flight wings"),
        ("SPIDER", "An eight-legged arachnid that produces silk"),
    ),
    "plants": (
        ("ROOT", "The plant organ that usually anchors it and absorbs water from soil"),
        ("STEM", "The plant axis that supports leaves and transports water and nutrients"),
        ("LEAF", "A usually flat plant organ that commonly performs photosynthesis"),
        ("FLOWER", "The reproductive structure of an angiosperm"),
        ("SEED", "A plant embryo enclosed with a protective covering and food supply"),
        ("POLLEN", "Grains containing the male gametophytes of seed plants"),
        ("PETAL", "One of the often colourful parts surrounding a flower's reproductive organs"),
        ("FRUIT", "A seed-bearing structure that develops from a flowering plant's ovary"),
        ("FERN", "A vascular plant reproducing by spores rather than seeds"),
        ("MOSS", "A small nonvascular land plant that reproduces by spores"),
        ("CACTUS", "A succulent plant of a family whose spines arise from specialised pads"),
        ("BARK", "The tissues outside the vascular cambium of a woody stem or root"),
    ),
    "ocean": (
        ("TIDE", "A periodic rise and fall of sea level driven mainly by lunar and solar gravity"),
        ("REEF", "A ridge of rock or coral close to the sea surface"),
        ("CORAL", "A marine animal whose colonies may build a limestone skeleton"),
        ("WHALE", "An aquatic mammal in the cetacean group that breathes air through a blowhole"),
        ("SHARK", "A fish with a cartilaginous skeleton and exposed gill slits"),
        ("OCTOPUS", "A soft-bodied marine mollusc with eight arms"),
        ("SQUID", "A marine mollusc with eight arms and two longer feeding tentacles"),
        ("PLANKTON", "Organisms that drift in water and cannot swim against the currents"),
        ("KELP", "A large brown seaweed that can form underwater forests"),
        ("CURRENT", "A directed movement of seawater"),
        ("SALT", "The common name for sodium chloride dissolved abundantly in seawater"),
        ("COAST", "The region where land meets the sea"),
    ),
}
# Additional authored vocabulary; these definitions are content, not solver proofs.
PACKS.update({
    "black hole": (
        ("GRAVITY", "The attraction associated with mass and energy"),
        ("EVENTHORIZON", "The boundary beyond which signals cannot escape a black hole"),
        ("ACCRETION", "The growth of an object by gathering surrounding matter"),
        ("SPACETIME", "The combined description of space and time in relativity"),
        ("PHOTON", "A quantum of electromagnetic radiation"),
        ("ORBIT", "A curved path around another body under gravity"),
        ("MASS", "A physical quantity associated with inertia and gravitation"),
        ("LENSING", "The bending of light paths by the gravity of intervening matter"),
        ("RADIATION", "Energy carried by waves or particles"),
        ("JET", "A narrow stream of matter expelled from some accreting systems"),
    ),
    "climate change": (
        ("CLIMATE", "The statistical pattern of weather over long periods"),
        ("WARMING", "An increase in average temperature"),
        ("EMISSIONS", "Substances released into the environment"),
        ("MITIGATION", "Actions that limit climate change by reducing its causes"),
        ("ADAPTATION", "Adjustment to actual or expected climate effects"),
        ("DROUGHT", "A prolonged shortage of precipitation relative to local conditions"),
        ("GLACIER", "A persistent mass of land ice that moves under its own weight"),
        ("SEALEVEL", "The height of the sea surface relative to a reference"),
        ("CARBONDIOXIDE", "A greenhouse gas with one carbon atom and two oxygen atoms"),
        ("METHANE", "A greenhouse gas with one carbon atom and four hydrogen atoms"),
    ),
    "photosynthesis": (
        ("CHLOROPHYLL", "A green pigment that absorbs light for photosynthesis"),
        ("SUNLIGHT", "Electromagnetic radiation reaching Earth from the Sun"),
        ("GLUCOSE", "A simple sugar with molecular formula C6H12O6"),
        ("OXYGEN", "A gas released when water is split in oxygenic photosynthesis"),
        ("WATER", "The compound H2O, used as an electron source in oxygenic photosynthesis"),
        ("LEAF", "A plant organ that commonly captures light for photosynthesis"),
        ("STOMATA", "Small pores that regulate gas exchange in plant surfaces"),
        ("THYLAKOID", "A membrane structure where photosynthetic light reactions occur"),
        ("CHLOROPLAST", "An organelle where photosynthesis occurs in plants and algae"),
        ("CARBONDIOXIDE", "The gas whose carbon is incorporated into sugars by carbon fixation"),
    ),
    "quantum computing": (
        ("QUBIT", "A unit of quantum information described using two basis states"),
        ("SUPERPOSITION", "A quantum state expressed as a combination of basis states"),
        ("ENTANGLEMENT", "A quantum correlation not describable by separate subsystem states"),
        ("GATE", "An operation applied to qubits in a quantum circuit"),
        ("REGISTER", "A collection of qubits treated together"),
        ("MEASUREMENT", "An operation producing a classical outcome from a quantum system"),
        ("CIRCUIT", "An ordered arrangement of quantum operations and measurements"),
        ("INTERFERENCE", "The addition of probability amplitudes, which can reinforce or cancel"),
        ("AMPLITUDE", "A complex coefficient used to describe a quantum state"),
        ("COHERENCE", "The preservation of relative phase relationships in a quantum state"),
    ),
})

ALIASES = {
    "astronomy": "space", "solar system": "space", "outer space": "space",
    "animal": "animals", "wildlife": "animals", "zoo": "animals",
    "plant": "plants", "botany": "plants", "garden": "plants",
    "sea": "ocean", "marine life": "ocean", "oceans": "ocean",
    "physics": "science", "mathematics": "puzzles", "maths": "puzzles",
    "math": "puzzles", "everyday objects": "riddles", "wonders": "space",
    "black holes": "black hole", "global warming": "climate change",
    "quantum computer": "quantum computing", "quantum computers": "quantum computing",
}
